SELECT [satisfaction]
      ,[Gender]
      ,[CustomerType]
      ,[Age]
      ,[TypeOfTravel]
      ,[Class]
      ,[FlightDistance]
      ,[SeatComfort]
      ,[DepartureArrivalTimeConvenient]
      ,[FoodAndDrink]
      ,[GateLocation]
      ,[InflightWifiService]
      ,[InflightEntertainment]
      ,[OnlineSupport]
      ,[EaseOfOnlineBooking]
      ,[OnBoardService]
      ,[LegRoomService]
      ,[BaggageHandling]
      ,[CheckinService]
      ,[Cleanliness]
      ,[OnlineBoarding]
      ,[DepartureDelayInMinutes]
      ,[ArrivalDelayInMinutes]
      ,[CleanedSatisfaction]
      ,[SentimentScore]
      ,[SentimentLabel]
  FROM [dbo].[CustomerProfile_Cleaned]